'use strict';var yy={TAB:0,Pj:1,vn:2},zy=function(a){Rb("MediaRouter.CastStreaming.Start.Success",a,yy)};var Ay=vb("mr.mirror.cast.LogUploader"),Cy=function(a,b,c){By("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},By=function(a,b,c,d){if(0==b.size)Ay.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);cw("https://clients2.google.com/cr/report",function(a){a=a.target;
var b=null;mw(a)?(b=nw(a),Ay.info("Upload to Crash succeeded: "+b)):Ay.info("Upload to Crash failed. HTTP status: "+a.La());d&&d(b)},"POST",e,void 0,3E4)}};var Dy=function(){this.b=0;Bj(this)},Fy=function(){Ey||(Ey=new Dy);return Ey},Gy=function(){var a=Fy(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.b&&c&&d-a.b<c?!1:Math.random()<b.fraction};Dy.prototype.xa=function(){return"mirror.cast.LogUtils"};Dy.prototype.Wa=function(){return[void 0,{lastAutoSubmitMillis:this.b}]};Dy.prototype.bb=function(){var a=zj(this);this.b=a&&a.lastAutoSubmitMillis||0};var Ey=null;vb("mr.mirror.cast.LogUtils");var Hy={Xv:"OFFER",os:"ANSWER",ww:"PRESENTATION",Zt:"GET_STATUS",ux:"STATUS_RESPONSE",Yt:"GET_CAPABILITIES",Ls:"CAPABILITIES_RESPONSE",Xw:"RPC"};var Iy=function(){this.capabilities=this.status=this.b=this.error=this.rpc=this.result=this.type=this.f=this.sessionId=null},Ly=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;Jy(JSON.parse(a),function(a){b=Ky(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},Ky=function(a){var b=new Iy;null!=a.sessionId&&(b.sessionId=String(a.sessionId));My(a.seqNum,function(a){b.f=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=na(Object.keys(Hy)),e=d.next();!e.done;e=d.next())if(Hy[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(Na(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}Jy(a.error,function(a){b.error=Ny(a)},function(){throw Error('"error" must be an Object');});Jy(a.answer,function(a){b.b=Oy(a)},function(){throw Error('"answer" must be an Object');});Jy(a.status,function(a){b.status=Py(a)},function(){throw Error('"status" must be an Object');
});Jy(a.capabilities,function(a){b.capabilities=Qy(a)},function(){throw Error('"capabilities" must be an Object');});return b},Jy=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},My=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Ry=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Sy=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Ty=function(){this.j=null;this.b=[];this.f=
[];this.h=this.g=this.s=null},Oy=function(a){var b=new Ty;My(a.udpPort,function(a){b.j=a},function(){throw Error('"answer.udpPort" must be a number');});Ry(a.sendIndexes,function(a){b.b=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Ry(a.ssrcs,function(a){b.f=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.s=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.h=String(a.castMode));
return b},Uy=function(){this.details=this.description=this.code=null},Ny=function(a){var b=new Uy;My(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Jy(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Vy=function(){this.f=this.b=null},Py=function(a){var b=new Vy;My(a.wifiSnr,function(a){b.b=a},function(){throw Error('"status.wifiSnr" must be a number');
});Ry(a.wifiSpeed,function(a){b.f=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Wy=function(){this.f=this.b=null},Qy=function(a){var b=new Wy;Sy(a.mediaCaps,function(a){b.b=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.f=a.map(function(a){var b;Jy(a,function(a){b=Xy(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},Yy=function(){this.h=this.m=this.s=this.j=this.u=this.b=this.o=this.f=this.initDataTypes=this.g=null},Xy=function(a){var b=new Yy;"keySystemName"in a&&(b.g=String(a.keySystemName));Sy(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Sy(a.codecs,function(a){b.f=a},function(){throw Error('"capabilities.codecs" must be an array');});Sy(a.secureCodecs,function(a){b.o=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Sy(a.audioRobustness,function(a){b.b=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Sy(a.videoRobustness,function(a){b.u=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.s=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var Zy=function(a){this.l=vb("mr.mirror.cast.MessageDispatcher");this.g=a;this.b=null;this.f=new Map;this.h=0},$y=function(a,b,c){if(a.f.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.f.set(b,c);a.h=0;Cb(a.l,"Added subscriber for "+b+"-type messages.");a.b||(a.b=xx(a.g),a.b.onMessage=a.j.bind(a))},az=function(a,b){a.f.delete(b)&&Cb(a.l,function(){return"Removed subscriber of "+b+"-type messages."});0==a.f.size&&a.b&&(a.b.Ta(),a.b=null)};
Zy.prototype.sendMessage=function(a){return this.b?"RPC"==a.type?this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var bz=function(a,b,c,d,e){var f=null,h=function(){az(a,c);null!=f&&(clearTimeout(f),f=null)};try{$y(a,c,function(a){e(a)&&h()})}catch(k){e(null,k);return}f=setTimeout(function(){h();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){h();e(null,a)})};
Zy.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=Ly(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.f.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.h?this.l.F(b):Cb(this.l,b);++this.h}};var cz=function(){this.b=Promise.resolve(1)},ez=function(a,b,c){return dz(a,function(a){return a==b},c)},fz=function(a,b){var c=[3,4];return dz(a,function(a){return-1!=c.indexOf(a)},b)},gz=function(a,b){a.b=a.b.catch(function(){return 1});return dz(a,function(){return!0},b)},dz=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.b=a.b.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new hz(a);try{var h=c(f)}catch(u){h=
Promise.reject(u)}return h.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.b)throw Error("A prior operation that started at "+(a+" did not complete."));return f.b})},function(a){e(a);throw a;});return f},hz=function(a){this.f=a;this.b=null},iz=function(a,b){a.b="number"===typeof b?b:a.f};var jz=chrome.cast.streaming,lz=function(a,b,c,d,e){this.H=a.sessionId;this.u=a.Mg;this.ia=a.Ve;this.h=b;this.G=c;this.D=d;this.M=kz(e,"onAnswer",this.u);this.Ja=kz(e,"onSessionStop",this.u);this.l=vb("mr.mirror.cast.StreamingLaunchWorkflow");this.B=new cz;this.m=this.A=this.o=this.f=this.b=this.s=this.j=this.g=null};
lz.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof mz,f=b instanceof mz;(e&&b&&!f||f&&a&&!e)&&Xb("Mixing remoting and non-remoting tracks");return ez(this.B,1,function(e){d.g=a;d.j=b;d.s=c;d.l.info(function(){return"Launching streaming for "+nz(d)+" "+("to a "+d.ia+".")});return oz(d).then(d.C.bind(d)).then(function(a){return pz(d,a).then(function(b){d.M();var c=qz(d,b,a);d.b=rz(d,d.b,c);d.f=rz(d,d.f,c);if(!d.b&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.A=!!b.g;d.m=function(a,b){a==d.b?d.s.Oe("Audio stream (id="+a+") error: "+b):a==d.f&&d.s.Oe("Video stream (id="+a+") error: "+b)};jz.rtpStream.onError.addListener(d.m);return sz(d,b,c)})}).then(function(){d.l.info(function(){return"Launched streaming for "+nz(d)});d.s.ig(d);iz(e,2);return{To:d.b,Lr:d.f}})})};
lz.prototype.stop=function(){var a=this;return gz(this.B,function(b){if(!a.g&&!a.j)return iz(b,1),Promise.resolve();a.l.info(function(){return"Stopping streaming for "+nz(a)+"."});a.m&&(jz.rtpStream.onError.removeListener(a.m),a.m=null);if(a.s){var c=a.s.Sg();a.s=null}else c=Promise.resolve();return c.then(function(){a.b&&(jz.rtpStream.stop(a.b),jz.rtpStream.destroy(a.b),a.b=null);a.f&&(jz.rtpStream.stop(a.f),jz.rtpStream.destroy(a.f),a.f=null);a.o&&(jz.udpTransport.destroy(a.o),a.o=null);a.Ja();
a.l.info(function(){return"Stopped streaming for "+nz(a)+"."});a.g=null;a.j=null;iz(b,1)})})};
var tz=function(a,b){var c=JSON.stringify(b);return Promise.all([a.b&&new Promise(function(b){return jz.rtpStream.getRawEvents(a.b,c,b)}),a.f&&new Promise(function(b){return jz.rtpStream.getRawEvents(a.f,c,b)})]).catch(function(b){a.l.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},uz=function(a){return Promise.all([a.b&&new Promise(function(b){return jz.rtpStream.getStats(a.b,b)}),a.f&&
new Promise(function(b){return jz.rtpStream.getStats(a.f,b)})]).catch(function(b){a.l.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[{}].concat(Na(a.filter(function(a){return!!a}))))})},nz=function(a){if(a.g&&a.j)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.j)b="video-only ";else return"stopped";return a.g instanceof mz||a.j instanceof mz?b+"remoting":b+"streaming"},oz=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(jz.rtpStream.destroy(c),c=null);e&&!a.j&&(jz.rtpStream.destroy(e),e=null);a.l.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.b=c;a.f=e;a.o=f;b()};a.g instanceof mz||a.j instanceof mz?jz.session.create(null,null,c):jz.session.create(a.g,a.j,c)})};
lz.prototype.C=function(){for(var a=zh(),b=zh(),c=[],d=na([this.b,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.b,h=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,n=f?48E3:9E4,u=na(jz.rtpStream.getSupportedParams(e)),z=u.next();!z.done;z=u.next())z=z.value,z.payload.payloadType=h,z.payload.maxLatency=this.h.maxLatencyMillis,z.payload.minLatency=this.h.minLatencyMillis,z.payload.animatedLatency=this.h.animatedLatencyMillis,z.payload.ssrc=
k,z.payload.clockRate=n,z.payload.aesKey=a,z.payload.aesIvMask=b,f?(z.payload.channels=2,z.payload.maxBitrate=this.h.audioBitrate,z.payload.maxFrameRate=100):(z.payload.minBitrate=this.h.minVideoBitrate,z.payload.maxBitrate=this.h.maxVideoBitrate,z.payload.maxFrameRate=this.h.maxFrameRate),c.push(new vz(e,z));return c};
var rz=function(a,b,c){b&&!c.some(function(a){return a.Qf==b})&&(a.l.F("Destroying RTP stream not selected by the receiver: id="+b),jz.rtpStream.destroy(b),b=null);return b},pz=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var h=b[f].params,k={index:f,codecName:h.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:h.payload.payloadType,ssrc:h.payload.ssrc,targetDelay:h.payload.animatedLatency,aesKey:h.payload.aesKey,aesIvMask:h.payload.aesIvMask,timeBase:"1/"+
h.payload.clockRate,receiverRtcpEventLog:a.h.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.h.dscpEnabled&&(k.receiverRtcpDscp=46);127==h.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<h.payload.maxBitrate?1E3*h.payload.maxBitrate:60*h.payload.maxFrameRate+h.payload.clockRate*h.payload.channels,sampleRate:h.payload.clockRate,channels:h.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*h.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*h.payload.maxBitrate,resolutions:[{width:a.h.maxWidth,height:a.h.maxHeight}]});e.push(k)}var n=a.g instanceof mz||a.j instanceof mz?"remoting":"mirroring",u={type:"OFFER",sessionId:a.H,seqNum:Dl(a.G),offer:{castMode:n,receiverGetStatus:!0,supportedStreams:e}};a.l.info(function(){return"Sending OFFER message: "+JSON.stringify(u)});bz(a.D,u,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.b){if(b.f!=u.seqNum)return a.l.F("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.b.h)&&e!=n||!e&&"mirroring"!=n)&&a.l.error("Expected receiver to ANSWER with castMode="+n+", but got: "+e);Cb(a.l,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.b)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},qz=function(a,b,c){if(b.b.length!=b.f.length)return a.l.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.b.length;e={candidate:e.candidate},++f){var h=b.b[f];if(0>h||h>=
c.length)return a.l.error("Receiver selected invalid index ("+h+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[h];if(d.some(function(a){return function(b){return b.Qf==a.candidate.Qf}}(e)))return a.l.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.f[h];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.l.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},sz=function(a,b,c){var d=null,e=function(){d&&(jz.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,h){var f=b.j||2344;a.l.info(function(){return"Starting RTP streams to receiver at "+(a.u+":"+f)+(" for selected offers: "+JSON.stringify(c))});var n=a.o||-1;a.h.dscpEnabled&&(a.l.info("Enabled DSCP in sender."),jz.udpTransport.setOptions(n,{DSCP:!0}));jz.udpTransport.setDestination(n,{address:a.u,port:f});var u=new Set(c.map(function(a){return a.Qf}));
d=function(a){u.delete(a);0==u.size&&e()};jz.rtpStream.onStarted.addListener(d);n=na(c);for(var z=n.next();!z.done;z=n.next())z=z.value,jz.rtpStream.toggleLogging(z.Qf,a.h.enableLogging),jz.rtpStream.start(z.Qf,z.params);setTimeout(function(){h(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},kz=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.l.error("Error from testHooks."+b,e)}}:function(){}},vz=function(a,b){this.Qf=
a;this.params=b},mz=function(){};var yz=function(a,b,c,d,e,f){this.m=a;this.D=wz(b,this.m.Cb);this.G=new lz(this.m.Cb,c,d,e,f);this.A=e;this.j=new cz;this.h=new xz;this.B=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.l=vb("mr.mirror.cast.MediaRemoter");this.u=this.b=this.s=this.g=this.C=null;this.f=!0;this.o=this.H.bind(this)};
yz.prototype.ab=function(a,b){var c=this;return ez(this.j,1,function(d){c.C=a;c.g=b;var e=c.B.createInterfacePtrAndBind();c.B.setConnectionErrorHandler(function(){c.l.info("Remoter mojo pipe connection error.");zz(c)});c.b=new mojo.MirrorServiceRemotingSourcePtr;var f=Rg(c.m.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.m.mediaSource);c.l.info("Connecting remoter to browser: tabId="+f);(zg.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.b));
c.b.ptr.setConnectionErrorHandler(function(){c.l.info("RemotingSource mojo pipe connection error.");zz(c)});return Az(c).then(function(){if(c.f)c.b.onSinkAvailable(c.D);iz(d,2)})})};
var zz=function(a){return gz(a.j,function(b){a.b&&(a.b.ptr.reset(),a.b=null);var c=a.s;a.s=null;a.g=null;a.C=null;a.B.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.o);return new Promise(function(d){window.setTimeout(function(){Bz(a).then(function(){iz(b,1);d();c&&c()})},250)})})};yz.prototype.mr=function(a){Cz(this.h,a)};yz.prototype.sendMessageToSink=yz.prototype.mr;yz.prototype.ig=function(a){this.g&&this.g.ig(a)};
yz.prototype.Sg=function(){return this.g?this.g.Sg():Promise.resolve()};yz.prototype.Oe=function(a,b){this.l.error("Error during streaming: "+a,b);if(this.b)this.b.onError();zz(this)};
yz.prototype.start=function(){var a=this,b=!1;this.l.info(function(){b=!0;return"Starting next media remoting session."});b&&Dz(this.h,function(b){return a.l.info(b)});Ez(this.h);ez(this.j,2,function(b){return(0,a.C)().then(function(c){a.s=c;$y(a.A,"RPC",function(b){if(b.rpc){var c=a.h;b=b.rpc;c.s&&(++c.m,c.f+=b.length,c.s(b))}});iz(b,3)}).catch(function(c){return Bz(a).then(function(){iz(b);throw c;})})}).then(function(){a.l.info("Remoting started successfully.")}).catch(function(b){a.l.error("Failed to start remoting",
b);a.b.onError()})};yz.prototype.start=yz.prototype.start;
yz.prototype.Dr=function(a,b){var c=this;return ez(this.j,3,function(d){return c.G.start(a?new mz:null,b?new mz:null,c).then(function(a){Fz(c.h,function(a){return c.A.sendMessage(a)},function(a){c.b.onMessageFromSink(a)});iz(d,4);return{audio_stream_id:a.To||-1,video_stream_id:a.Lr||-1}}).catch(function(a){return Bz(c).then(function(){iz(d);throw a;})})}).catch(function(a){c.l.error("Failed to start remoting streams",a);zz(c);return{audio_stream_id:-1,video_stream_id:-1}})};
yz.prototype.startDataStreams=yz.prototype.Dr;yz.prototype.stop=function(a){var b=this;fz(this.j,function(c){b.b.onStopped(a);return Bz(b).then(function(){b.l.info("Remoting stopped.");iz(c,5);(0,b.s)().then(function(){return ez(b.j,5,function(a){if(b.b&&b.f)b.b.onSinkAvailable(b.D);iz(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.s=null})}).catch(function(a){b.l.error("Failed to stop remoting: ",a);zz(b)})};yz.prototype.stop=yz.prototype.stop;
yz.prototype.np=function(){null===this.u&&(this.u=Te(this.m.Cb.Mg).then(function(a){return a.f||!1}));return this.u.then(function(a){return{rate:(a?1E7:5E6)/8}})};yz.prototype.estimateTransmissionCapacity=yz.prototype.np;
var Bz=function(a){return a.G.stop().then(function(){az(a.A,"RPC");Gz(a.h);Hz(a.h)})},Az=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.l.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.l.error("Pref value not a boolean: "+JSON.stringify(c)):(a.f=!!c.value,a.l.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.f));chrome.settingsPrivate.onPrefsChanged.hasListener(a.o)||chrome.settingsPrivate.onPrefsChanged.addListener(a.o);b()})})};
yz.prototype.H=function(a){if(this.b){a=na(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.l.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.f==a)break;this.f=a;this.l.info("mediaRemotingEnabled_ changed to: "+this.f);if(this.f)this.b.onSinkAvailable(this.D);else this.b.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var wz=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.Cr||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,h=d.audio_capabilities,k=d.video_capabilities,n=b.Ve||"";(a.b||[]).forEach(function(a){switch(a){case "audio":h.push(e.CODEC_BASELINE_SET);break;case "aac":h.push(e.CODEC_AAC);break;case "opus":h.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":n.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":n.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:c.l.info("Unknown mediaCap name: "+a)}});b.Ve&&"Chromecast Ultra"==b.Ve&&k.push(f.SUPPORT_4K);return d},xz=function(){this.s=this.j=this.b=null;this.u=this.f=this.m=this.h=this.o=0;this.g=null},Ez=function(a){a.b=[];Iz(a,performance.now())},Fz=function(a,b,c){a.j=b;a.s=
c;a.b?(b=a.b,a.b=null,b.forEach(function(b){return Cz(a,b.data).then(b.pr,b.rm)})):Iz(a,performance.now())},Gz=function(a){if(a.b){var b=Error("Stop before delivering pending message");a.b.forEach(function(a){return a.rm(b)});a.b=null}a.j=null;a.s=null},Cz=function(a,b){if(a.j){var c=btoa(String.fromCharCode.apply(null,b));++a.o;a.h+=b.length;return a.j({type:"RPC",rpc:c})}return a.b?new Promise(function(c,e){a.b.push({data:b,pr:c,rm:e})}):Promise.reject(Error("RPC pipe not started"))},Dz=function(a,
b){Hz(a);a.g=setInterval(function(){if(a.b)var c=a.b.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.u)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec) and ")+("received "+a.m+" messages ("+Math.round(a.f/d)+" ")+"bytes/sec).";Iz(a,c);c=d}b(c)},3E4)},Hz=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},Iz=function(a,b){a.o=0;a.h=0;a.m=0;a.f=0;a.u=b};var Jz=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Kz=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Lz=function(a,b,c,d,e){this.h=new lz(a,b,c,d,void 0===e?null:e);this.l=vb("mr.mirror.cast.MediaStreamer");this.j=new cz;this.g=this.f=this.b=this.s=null};Lz.prototype.start=function(a,b){var c=this;return ez(this.j,1,function(d){c.s=a;c.b=Jz(a);c.b&&"ended"==c.b.readyState&&(c.b=null);c.f=Kz(a);c.f&&"ended"==c.f.readyState&&(c.f=null);if(!c.b&&!c.f)return iz(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.h.start(c.b,c.f,c.g).then(function(){return iz(d,2)})})};
Lz.prototype.stop=function(){var a=this;return gz(this.j,function(b){return a.h.stop().then(function(){a.b=null;a.f=null;a.s=null;a.g=null;iz(b,1)})})};var Mz=function(a){return ez(a.j,2,function(b){a.l.info("Suspending media streaming...");return a.h.stop().then(function(){a.l.info("Suspended media streaming.");iz(b,3)})})};
Lz.prototype.resume=function(){var a=this;return ez(this.j,3,function(b){a.b&&"ended"==a.b.readyState&&(a.b=null);a.f&&"ended"==a.f.readyState&&(a.f=null);if(!a.b&&!a.f)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.l.info("Resuming media streaming...");return a.h.start(a.b,a.f,a.g).then(function(){a.l.info("Resumed media streaming.");iz(b,2)})})};var Nz=function(a,b,c){this.j=a;this.g=b;this.h=c;this.l=vb("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.f=[]};Nz.prototype.start=function(){var a=this;null==this.b&&(Cb(this.l,"Starting Wifi Status Monitoring."),this.f=[],$y(this.h,"STATUS_RESPONSE",function(b){return Oz(a,b)}),this.b=setInterval(function(){return Pz(a)},12E4),Pz(this))};Nz.prototype.stop=function(){null!=this.b&&(Cb(this.l,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,az(this.h,"STATUS_RESPONSE"))};
var Oz=function(a,b){if(null!=a.b)if(b.status){var c={};null!=b.status.b&&(c.wifiSnr=b.status.b);null!=b.status.f&&(c.wifiSpeed=b.status.f[3]);0==Object.keys(c).length?a.l.F(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.f.length&&a.f.shift(),a.f.push(c),a.l.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.l.F(function(){return"Ignoring response without status: "+JSON.stringify(b)})},Pz=function(a){a.h.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:Dl(a.g),get_status:["wifiSnr","wifiSpeed"]})};var Qz=function(a,b,c,d){this.D=b.Mg;this.m={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:gh(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Ve};this.C=c;this.A=d;this.g=this.f=this.o=this.s=this.j=this.u=this.h=null;this.b=[]};Qz.prototype.ig=function(a){null!=this.f&&clearInterval(this.f);this.h=a;this.u=Date.now();this.f=setInterval(this.B.bind(this,a),9E5)};
Qz.prototype.Sg=function(){null!=this.f&&(clearInterval(this.f),this.f=null);if(null!=this.h){var a=this.B(this.h);this.h=null;return a}return Promise.resolve()};Qz.prototype.Oe=function(a,b){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.s=a():"string"===typeof a&&(this.s=a),b&&"string"===typeof b.stack&&(this.o=b.stack))};
var Sz=function(a,b){return(null==a.h?Promise.resolve():a.B(a.h)).then(function(){var c=b.map(function(b){b=Rz(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.Of}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),Of:new Blob(d,{type:"application/json"})}});a.b=[];return c})};
Qz.prototype.B=function(a){var b=this;if(null!=this.g)return this.g;var c=Te(this.D).then(function(c){c={receiverVersion:c.b,receiverConnected:c.g,receiverOnEthernet:c.f,receiverHasUpdatePending:c.h,receiverUptimeSeconds:c.j};Object.assign(c,b.m);var d=Date.now();Object.assign(c,{startTime:b.u,endTime:d,activity:nz(a),receiverWifiStatus:Array.from(b.A.f)});b.u=d;null!=b.j&&(Object.assign(c,{streamingErrorTime:b.j,streamingErrorMessage:b.s,streamingErrorCause:b.o}),b.j=null,b.s=null,b.o=null);return c});
return(this.g=Promise.all([c.then(function(b){return tz(a,b)}),c,uz(a)]).then(function(a){var c=na(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.b.push({events:a,Of:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.b=Rz(b,b.C);b.g=null}))||Promise.resolve()};
var Rz=function(a,b){b-=2;for(var c=[],d=a.b.length-1;0<=d;--d){b-=a.b[d].Of.size+1;if(0>b)break;c.push({events:null,Of:a.b[d].Of});if(null!=a.b[d].events){var e=a.b[d].events.size;b>=e&&(c[c.length-1].events=a.b[d].events,b-=e)}}return c.reverse()};var Tz=vb("mr.NetworkUtils"),Uz=function(a,b){return jg?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(Tz.F("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(Tz.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var Vz=function(a,b,c,d){d=void 0===d?null:d;dh.call(this,b);var e=b.Cb;this.B=e.sessionId;this.D=e.Mg;this.C=a;this.H=d;this.l=vb("mr.mirror.cast.Session");this.o=new cz;this.m=new Cl("mirror.cast.SeqNumGenerator");this.s=new Zy(b.id);this.j=new Lz(e,this.C,this.m,this.s,this.H);this.g=null;this.b=new Qz(a,e,c,new Nz(this.B,this.m,this.s));this.f=!1;this.A=null};l(Vz,dh);g=Vz.prototype;
g.start=function(a){var b=this;return ez(this.o,1,function(c){var d=new Gb("MediaRouter.CastStreaming.Session.Launch");return Wz(b).then(function(c){b.f=c;return b.j.start(a,b)}).then(function(){if(b.j.h.A){var a=b.b;a.m.tdlsIsOn=b.f;a.A.start();Xz(b)}else b.b.m.tdlsIsOn=b.f;d.b();b.A=new Nb("MediaRouter.CastStreaming.Session.Length");iz(c,2);return b})})};
g.stop=function(){var a=this;return gz(this.o,function(b){a.A&&(a.A.b(),a.A=null);a.b.A.stop();return a.j.stop().then(function(){return a.g?zz(a.g):Promise.resolve()}).then(function(){a.g=null;return a.f?Yz(a):Promise.resolve()}).then(function(){a.f=!1;iz(b,4)})})};g.pm=function(){var a={sessionId:this.B,seqNum:Dl(this.m),type:"PRESENTATION",icons:[],title:bh(this.hc)};this.l.info("Sending session metadata update to receiver: "+this.B);this.s.sendMessage(a)};g.ig=function(a){this.b.ig(a)};g.Sg=function(){return this.b.Sg()};
g.Oe=function(a,b){this.b.Oe(a,b);this.l.error(a,b);this.stop()};
var Zz=function(a,b){return Sz(a.b,b)},Wz=function(a){return a.C.useTdls?Uz(a.D,!0).then(function(b){if("Connected"==b)return a.l.info("Successfully enabled TDLS."),!0;a.l.F("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.l.F("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Yz=function(a){return Uz(a.D,!1).catch(function(b){return a.l.error("Error while turning TDLS back off",b)})},Xz=function(a){$z(a).then(function(b){(b.b||[]).includes("video")?aA(a,b):a.l.F(function(){return"Receiver incapable of Media Remoting: "+
JSON.stringify(b)})}).catch(function(b){a.l.F("None/Invalid capabilites response. Media Remoting disabled.",b)})},$z=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.B,seqNum:Dl(a.m)};a.l.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});bz(a.s,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.f!=d.seqNum)return a.l.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+
JSON.stringify(e)}),!1;Cb(a.l,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},aA=function(a,b){ez(a.o,2,function(c){var d=a.h.Cb.Ve||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.l.F("HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),iz(c),Promise.resolve();a.g=new yz(a.h,b,a.C,a.m,a.s,a.H);return a.g.ab(a.M.bind(a),a).catch(function(b){a.l.error("Media Remoting start failed: "+
b.message,b)}).then(function(){return iz(c)})})};Vz.prototype.M=function(){var a=this;return ez(this.o,2,function(b){return new Promise(function(c,d){Mz(a.j).then(function(){iz(b,3);a.G=!0;Zg(a);c(a.Ja.bind(a))}).catch(function(b){a.Oe("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
Vz.prototype.Ja=function(){var a=this;return ez(this.o,3,function(b){return new Promise(function(c,d){a.j.resume().then(function(){iz(b,2);a.G=!1;Zg(a);c()}).catch(function(b){a.Oe("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var bA=function(){Sg.call(this,"cast_streaming")};l(bA,Sg);g=bA.prototype;g.getName=function(){return"cast_streaming"};g.lh=function(a,b){return new Vz(a,b,20969472,null)};g.Xh=function(){zy(0)};g.Uh=function(){zy(1)};g.sj=function(){zy(2)};g.Vh=function(){Qb("MediaRouter.CastStreaming.Session.End")};g.Wh=function(a){Rb("MediaRouter.CastStreaming.Start.Failure",a,fg)};g.Jg=function(){Qb("MediaRouter.CastStreaming.Stream.End")};
g.ri=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&Gy(),e=[9351424];d&&e.push(20969472);return Zz(a,e).then(function(a){var e=a[a.length-1];a=Kj(a[0].events).catch(function(a){b.L.error("Failed to persist events Blob.",a)});d&&0<e.events.size?Cy(e.events,void 0,b.gq.bind(b)):c&&By("stats.json",e.Of,void 0,void 0);return a})})};g.gq=function(a){a&&(Fy().b=Date.now())};
g.dj=function(a){this.L.info("Received message to upload logs for "+a);return this.b?Zz(this.b,[20969472]).then(function(b){b=na(b).next().value;return 0==b.events.size?"":Cy(b.events,a)}):Promise.resolve(cA(this,a))};
var cA=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return Kj(new Blob),a.L.info("Uploading saved logs for feedback."),Cy(c,b)},dA=new bA;Ig("mr.mirror.cast.Service",dA);
